# Generated by Django 5.0.6 on 2024-05-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_donut_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='nutritional_information',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
