# Generated by Django 5.0.6 on 2024-06-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_donut_nutritional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='nutritional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
