# Generated by Django 5.0.6 on 2024-06-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_donut_nutritional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
