# Generated by Django 5.0.6 on 2024-06-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_donut_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='date_expirity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
