# Generated by Django 5.0.6 on 2024-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_profits_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profits',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=999),
        ),
    ]
