# Generated by Django 5.0.6 on 2024-05-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='suggestion',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
