# Generated by Django 5.0.6 on 2024-06-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0004_order_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Process'), ('ST', 'Sent'), ('DV', 'Delivered')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
