# Generated by Django 5.0.6 on 2024-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0005_remove_order_delivered_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='suggestion',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
