# Generated by Django 5.0.4 on 2024-04-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='EstatusPago',
            field=models.BooleanField(default=False),
        ),
    ]
