# Generated by Django 5.0.4 on 2024-04-16 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_pedidos_estatuspago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='Precio',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Costo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='task.tipodeservicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodeservicio',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servicio', to='task.tipodeservicio'),
        ),
    ]
