# Generated by Django 5.0.4 on 2024-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_carritoitem_producto_remove_pedidos_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='address',
            field=models.CharField(default='Dirección predeterminada', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cvc',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='cliente',
            name='debito',
            field=models.CharField(default='0000-0000-0000-0000', max_length=16),
        ),
        migrations.AddField(
            model_name='cliente',
            name='due_date',
            field=models.CharField(default='31/12/2025', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estate',
            field=models.CharField(default='Estado predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='postalcode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
