# Generated by Django 5.0.4 on 2024-05-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_cliente_direccion_cliente_address_cliente_cvc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
