# Generated by Django 5.0.4 on 2024-05-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='precio_unitario',
        ),
    ]
