# Generated by Django 5.0.4 on 2024-05-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_carritoitem_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='due_date',
        ),
    ]
