# Generated by Django 5.0.4 on 2024-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_orden_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.CharField(default='Sin productos', max_length=255),
        ),
    ]
